### ISSUE TITLE
[1.6.1] Server Crash - Invalid resource path in FTB Quest config - Non [a-z0-9/._-] character in path

### ISSUE THREAD

**Issue by TigerWalts** [chocolate-edition/Public-Issue-Board#6]
Either the server is more strict about (or doesn't catch and ignore) this error or we have disabled a mod that makes Minecraft allow upper case in resource paths.

```
net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: chocolate:textures/wardingpearlTitle.png
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[server-1.19.2-20220805.130853-srg.jar%23661!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:A}
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42) ~[server-1.19.2-20220805.130853-srg.jar%23661!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ftblibrary-common.mixins.json:ResourceLocationMixin,pl:mixin:APP:rhino-common.mixins.json:ResourceLocationMixin,pl:mixin:A}
	at dev.ftb.mods.ftblibrary.icon.Icon.getIcon0(Icon.java:199) ~[ftb-library-forge-1902.4.1-build.236.jar%23506!/:1902.4.1-build.236] {re:classloading}
```

Tracked it down to `config/ftbquests/quests/chapters/blue_skies_utilities.snbt:327`:

```snbt
		{
			click: ""
			corner: false
			dev: false
			height: 1.0d
			hover: [ ]
			image: "chocolate:textures/wardingpearlTitle.png"
			rotation: 0.0d
			width: 6.895522388059701d
			x: -5.75d
			y: 18.5d
		}
```

The correct path is `chocolate:textures/wardingpearltitle.png`.

**Comment by Jonah-Hansen** [comment]
this is fixed in 1.6.2, although you should be using the server pack for the server, not the client pack
